name: Build and Deploy

on:
  push:
    branches: main

jobs:
  build:
    name: Build and deploy Gatsby site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "v20.11.0"

      - name: Install Dependencies
        run: npm install

      - name: Install Gatsby CLI
        run: npm install -g gatsby-cli

      - name: Build
        run: gatsby build

      - name: Verify build
        run: ls -la public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "${{ secrets.HOST }}" >> ~/.ssh/known_hosts

      - name: SFTP upload
        run: sftp -i ~/.ssh/id_rsa student09@${{ secrets.HOST }} <<< $'cd site/html \n put -r /mnt/c/users/aymie/Documents/GitHub/first-gatsby-site/public/'
#a comment
