name: Build and Deploy

on:
  push:
    branches: main

jobs:
  build:
    name: Build and deploy Gatsby site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build
        run: gatsby build

      - name: Verify build
        run: ls -la public

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/github_deploy_key
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "${{ secrets.HOST }}" >> ~/.ssh/known_hosts
          grep -q "${{ secrets.HOST }}" ~/.ssh/known_hosts || ssh-keyscan -H "${{ secrets.HOST }}" >> ~/.ssh/known_hosts

      - name: Use SSH Key for Deployment
        env:
          SSH_PRIVATE_KEY_PATH: ~/.ssh/id_rsa
        run: |
          ssh student09@foo.wendell.tech rsync -avh /mnt/c/users/aymie/Documents/GitHub/first-gatsby-site/public/. student09@foo.wendell.tech:site/html
