name: Build and Deploy

on:
  push:
    branches: master

jobs:
  build:
    name: Build and deploy Gatsby site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.11.0"

      - name: Install Project Dependencies
        run: npm ci
      - name: Install Gatsby CLI
        run: npm install -g gatsby-cli@5.13.2

      - name: Build
        run: gatsby build

      - name: Verify build
        run: ls -la public

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/github_deploy_key
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "${{ secrets.HOST }}" >> ~/.ssh/known_hosts
          grep -q "${{ secrets.HOST }}" ~/.ssh/known_hosts || ssh-keyscan -H "${{ secrets.HOST }}" >> ~/.ssh/known_hosts

      - name: Use SSH Key for Deployment
        env:
          SSH_PRIVATE_KEY_PATH: ~/.ssh/id_rsa # Change this to the appropriate path for your SSH key
        run: |
          ssh student09@foo.wendell.tech "command_to_deploy"
